CREATE TABLE users (
	`id` INT UNSIGNED AUTO_INCREMENT NOT NULL,
	`email` VARCHAR(50) UNIQUE NOT NULL,
	`password` VARCHAR(255) NOT NULL,
  `date` DATE DEFAULT NOW() NOT NULL,

	CONSTRAINT users_id_pk PRIMARY KEY(id)
);